import type { MapLabels } from './types'

/** Libellés par défaut (français) — chaque clé est overridable via `<MapProvider labels>`. */
export const defaultLabels: MapLabels = {
  controls: {
    pan: 'Déplacer la carte',
    rotate: 'Pivoter la vue (MAJ)',
    north: 'Nord / vue du dessus',
    zoomIn: 'Zoom avant',
    zoomOut: 'Zoom arrière',
    tilt: 'Incliner',
    topDown: 'Vue du dessus',
    globe: 'Retour au globe',
    fullscreen: 'Plein écran',
  },
  tags: {
    button: 'Couches — filtrer par tag',
    searchPlaceholder: 'Rechercher un tag…',
    empty: 'Aucun tag sur la carte',
    noMatch: 'Aucun tag ne correspond',
    showAll: 'Tout afficher',
  },
  search: {
    placeholder: 'Rechercher un lieu…',
    inputLabel: 'Recherche',
  },
  toolbar: {
    navigate: 'Naviguer',
    undo: 'Annuler',
    redo: 'Rétablir',
    clearAll: 'Tout effacer',
  },
  tools: {
    select: 'Sélectionner',
    line: 'Ligne',
    polygon: 'Polygone',
    rect: 'Rectangle',
    circle: 'Cercle',
    freehand: 'Main levée',
    arrow: 'Flèche',
    measure: 'Mesurer',
    erase: 'Effacer',
  },
  selectModes: {
    rect: { label: 'Rectangle', description: 'Sélection par rectangle' },
    poly: { label: 'Polygone', description: 'Sélection par polygone' },
    lasso: { label: 'Lasso', description: 'Sélection au lasso' },
  },
  style: {
    fill: 'Couleur de fond',
    stroke: 'Couleur de bordure',
    swap: 'Échanger fond et bordure',
    color: 'Couleur {color}',
    customColor: 'Couleur personnalisée',
    border: 'Bordure',
    noBorder: 'Pas de bordure',
    borderWidth: 'Bordure {width} px',
    strokeStyle: 'Trait',
    solid: 'Trait plein',
    dashed: 'Tirets',
    dotted: 'Pointillés',
    strokeOpacity: 'Op. trait',
    fillOpacity: 'Fond',
    opacityPreset: 'Fond {percent} %',
    corners: 'Angles',
    cornerRadius: 'Angles arrondis {radius} %',
    selectionCount: '{count} forme',
    selectionCountPlural: '{count} formes',
  },
  settings: {
    title: 'Réglages des outils',
    resetAll: 'Tout réinitialiser',
    resetTool: 'Réinitialiser cet outil',
    shortcutsTitle: 'Raccourcis clavier',
  },
  actions: {
    panMap: 'Déplacer la carte',
    rotateCamera: 'Tourner la caméra',
    rotateShape: 'Tourner la forme',
    undoRedo: 'Annuler / Rétablir',
    selectAll: 'Tout sélectionner',
    duplicate: 'Dupliquer',
    delete: 'Supprimer',
    moveSelection: 'Déplacer la sélection',
    closePolygon: 'Fermer le polygone',
    cancel: 'Annuler / quitter',
  },
  keys: {
    escape: 'Échap',
    space: 'Espace',
    spaceShift: 'Espace+Maj',
    shiftDrag: 'Maj + glisser',
    enter: 'Entrée',
    arrows: 'Flèches',
    backspace: '⌫',
  },
  format: {
    shortcut: '{label} ({key})',
  },
  measure: {
    kilometers: '{value} km',
    meters: '{value} m',
  },
  errors: {
    outsideMap: 'Ce composant doit être utilisé à l’intérieur de <Map>',
  },
}
