import type { MapLabels } from './types'

/** Libellés par défaut (français) — chaque clé est overridable via `<MapProvider labels>`. */
export const defaultLabels: MapLabels = {
  controls: {
    pan: 'Déplacer la carte',
    rotate: 'Pivoter la vue (MAJ)',
    north: 'Nord / vue du dessus',
    zoomIn: 'Zoom avant',
    zoomOut: 'Zoom arrière',
    tilt: 'Incliner',
    graticule: 'Grille de coordonnées',
    globe: 'Retour au globe',
    fullscreen: 'Plein écran',
    target: 'Revenir à la cible',
    mode3d: 'Vue 3D',
    traffic: 'Trafic',
    pedestrian: 'Mode piéton',
    pedestrianExit: 'Quitter le mode piéton',
    immersion: 'Immersion totale',
    pedestrianHint: 'Échap pour quitter',
  },
  tags: {
    button: 'Couches — filtrer par tag',
    searchPlaceholder: 'Rechercher un tag…',
    empty: 'Aucun tag sur la carte',
    noMatch: 'Aucun tag ne correspond',
    showAll: 'Tout afficher',
  },
  catalog: {
    button: 'Catalogue',
    searchPlaceholder: 'Taper votre recherche…',
    empty: 'Aucun élément',
    noMatch: 'Aucun résultat',
    loading: 'Chargement…',
    error: 'Chargement impossible',
    retry: 'Réessayer',
    itemError: 'Impossible d’afficher cet élément',
    add: 'Afficher {label} sur la carte',
    remove: 'Retirer {label} de la carte',
    focus: 'Centrer sur {label}',
    expand: 'Déplier',
    collapse: 'Replier',
    groupCount: '{shown}/{total}',
    groupCountLabel: '{shown} élément(s) sur {total} affiché(s)',
    sourceShown: '{count} élément(s) de cette source sur la carte',
    numberLocale: 'auto',
    settings: {
      title: 'Catalogue',
      persist: 'Conserver les éléments affichés entre les sessions',
      fitOnAdd: 'Cadrer à l’ajout',
      clear: 'Tout retirer',
    },
  },
  symbols: {
    button: 'Symboles',
    searchPlaceholder: 'Rechercher un symbole…',
    dragHint: 'Glissez une icône sur la carte pour la poser',
    noMatch: 'Aucun symbole ne correspond',
    affiliation: 'Affiliation',
    multiPointHint: 'Tracé multi-points — bientôt disponible',
    delete: 'Supprimer',
    categories: {
      installations: 'Installations',
      units: 'Unités',
      equipment: 'Équipements',
      air: 'Aérien',
      events: 'Événements',
      control: 'Points de contrôle',
      'tactical-graphics': 'Graphiques tactiques',
    },
    affiliations: {
      friendly: 'Ami',
      hostile: 'Hostile',
      neutral: 'Neutre',
      unknown: 'Inconnu',
    },
    // Vide : les textes du catalogue par défaut SONT en français. Une application
    // anglophone y met ses traductions, clé par clé.
    catalog: {},
  },
  plugins: {
    button: 'Plugins',
    title: 'Plugins',
    empty: 'Aucun plugin disponible',
    toggle: 'Activer {name}',
    reset: 'Réinitialiser',
    clear: 'Tout désactiver',
  },
  templates: {
    title: 'Templates',
    save: 'Sauvegarder',
    saveHint: 'Nommez ce template et choisissez ce qu’il contient',
    name: 'Nom du template',
    empty: 'Aucun template',
    delete: 'Supprimer {name}',
    deleteConfirm: 'Supprimer « {name} » ? Cette action est définitive.',
    confirm: 'Confirmer',
    cancel: 'Annuler',
    rename: 'Renommer {name}',
    update: 'Mettre à jour « {name} » avec le dessin courant',
    updateConfirm: 'Mettre à jour « {name} » avec le dessin courant ? L’ancien contenu sera écrasé.',
    apply: 'Charger ce template',
    applyMode: 'Au clic sur un template :',
    merge: 'Ajouter',
    replace: 'Remplacer',
    remove: 'Retirer',
    export: 'Exporter en fichier .m3dt',
    import: 'Importer',
    shared: 'Partagé',
    readOnly: 'Lecture seule',
    defaultName: 'template',
    importedName: 'Import',
    category: { shapes: 'Formes', freehand: 'Crayon', symbols: 'Symboles' },
    stats: { pair: '{label} {count}', bytes: '{count} o' },
    view: 'Vue',
    viewHint: 'Position, orientation, type de carte et couches affichées',
    hasView: 'Ce template rouvre sa vue',
  },
  search: {
    placeholder: 'Rechercher sur la carte…',
    inputLabel: 'Recherche',
    noResults: 'Aucun résultat',
    noResultsInGroup: 'Aucun résultat dans « {group} »',
    historyTitle: 'Recherches récentes',
    clearHistory: 'Effacer l’historique',
    clearInput: 'Effacer la recherche',
    scopeAll: 'Tout',
    scopeLabel: 'Restreindre la recherche',
    groups: {
      shape: 'Zones',
      draw: 'Dessins',
      symbol: 'Symboles',
      place: 'Lieux',
    },
  },
  toolbar: {
    navigate: 'Naviguer',
    undo: 'Annuler',
    redo: 'Rétablir',
    clearAll: 'Tout effacer',
    clearAllDescription: 'Effacer tout ce que la gomme peut effacer',
  },
  tools: {
    select: 'Sélectionner',
    line: 'Ligne',
    polygon: 'Polygone',
    rect: 'Rectangle',
    circle: 'Cercle',
    freehand: 'Crayon',
    arrow: 'Flèche',
    measure: 'Mesurer',
    erase: 'Effacer',
    symbol: 'Symboles',
  },
  selectModes: {
    rect: { label: 'Rectangle', description: 'Sélection par rectangle' },
    poly: { label: 'Polygone', description: 'Sélection par polygone' },
    lasso: { label: 'Lasso', description: 'Sélection au lasso' },
  },
  eraseModes: {
    point: { label: 'Gomme', description: 'Effacer un élément au clic' },
    select: { label: 'Gomme sélection', description: 'Effacer tout ce que la sélection touche' },
  },
  buildingPick: { label: 'Bâtiment', description: 'Sélectionner un bâtiment (volume 3D interne)' },
  measureTools: {
    measure: { label: 'Mesurer', description: 'Mesurer une distance' },
  },
  graticule: {
    remarkable: {
      equator: 'Équateur',
      tropicCancer: 'Tropique du Cancer',
      tropicCapricorn: 'Tropique du Capricorne',
      arcticCircle: 'Cercle arctique',
      antarcticCircle: 'Cercle antarctique',
      primeMeridian: "Méridien d'origine",
      antimeridian: '180ᵉ méridien',
    },
    // Guillemets simples pour la minute et doubles pour la seconde : c'est la notation des
    // cartes, et elle ne se traduit pas — seuls les points cardinaux le font.
    format: { deg: '{d}°{hemi}', dm: "{d}°{m}'{hemi}", dms: '{d}°{m}\'{s}"{hemi}' },
    hemisphere: { north: 'N', south: 'S', east: 'E', west: 'W' },
  },
  style: {
    fill: 'Couleur de fond',
    stroke: 'Couleur de bordure',
    swap: 'Échanger fond et bordure',
    color: 'Couleur {color}',
    customColor: 'Couleur personnalisée',
    border: 'Bordure',
    noBorder: 'Pas de bordure',
    borderWidth: 'Bordure {width} px',
    strokeStyle: 'Trait',
    solid: 'Trait plein',
    dashed: 'Tirets',
    dotted: 'Pointillés',
    strokeOpacity: 'Op. trait',
    fillOpacity: 'Fond',
    opacityPreset: 'Fond {percent} %',
    corners: 'Angles',
    cornerRadius: 'Angles arrondis {radius} %',
    selectionCount: '{count} forme',
    selectionCountPlural: '{count} formes',
    expand: 'Modifier le style',
  },
  selection: {
    title: 'Sélection',
    shapesGroup: 'Formes',
    group: '{group} · {type}',
    deselectGroup: 'Désélectionner {label}',
    clearAll: 'Tout désélectionner',
    movePanel: 'Déplacer le panneau',
    expandGroup: 'Déplier / replier {label}',
    shapeItem: '{type} {n}',
    delete: 'Supprimer',
    pathsGroup: 'Tracés',
    pathItem: 'Tracé {n}',
  },
  clusters: {
    label: 'Groupe de {count} marqueurs',
    labelSingular: 'Groupe de {count} marqueur',
  },
  markerList: {
    target: 'Cibler',
    actions: 'Actions pour {label}',
    remove: 'Retirer {label}',
  },
  lens: {
    tool: 'Loupe',
    title: '{count} marqueurs',
    titleSingular: '{count} marqueur',
    empty: 'Aucun marqueur dans la zone',
    remove: 'Retirer la loupe',
    movePanel: 'Déplacer le panneau',
    snapBack: 'Rattacher le panneau à la zone',
    hidden: 'Masqué au zoom actuel',
  },
  settings: {
    title: 'Réglages des outils',
    resetAll: 'Tout réinitialiser',
    resetTool: 'Réinitialiser cet outil',
    shortcutsTitle: 'Raccourcis clavier',
    preferences: {
      title: 'Préférences',
      reset: 'Réinitialiser les préférences',
      quality: {
        title: 'Qualité 3D',
        auto: 'Auto',
        high: 'Élevé',
        medium: 'Moyen',
        low: 'Léger',
      },
      controls: {
        title: 'Contrôles',
        move: 'Déplacement',
        view: 'Vue',
        speed: 'Vitesse',
        slow: 'Lent',
        normal: 'Normal',
        fast: 'Rapide',
        damping: 'Glissement de la carte',
        rebind: 'Changer la touche : {action}',
        conflict: 'Touche déjà utilisée ({action})',
        conflictOther: 'Touche déjà utilisée par une autre commande',
        resetKeys: 'Réinitialiser les touches',
      },
      actions: {
        forward: 'Avancer',
        backward: 'Reculer',
        left: 'Gauche',
        right: 'Droite',
        boost: 'Accélérer (piéton)',
        north: 'Nord',
        tilt: 'Inclinaison',
        globe: 'Globe',
        zoomIn: 'Zoom avant',
        zoomOut: 'Zoom arrière',
        fullscreen: 'Plein écran',
      },
    },
    capture: {
      title: 'Prendre une photo',
      format: 'Format',
      quality: 'Qualité',
      scale: 'Netteté',
      transparent: 'Fond transparent',
      download: 'Télécharger',
      mail: 'Envoyer par mail',
      share: 'Partager',
      filename: 'carte',
    },
  },
  actions: {
    panMap: 'Déplacer la carte',
    navigate: 'Se déplacer (caméra)',
    boost: 'Accélérer',
    zoom: 'Zoom avant / arrière',
    basemap: 'Vue 3D / plan',
    layers: 'Couches',
    rotateCamera: 'Tourner la caméra',
    rotateShape: 'Tourner la forme',
    undoRedo: 'Annuler / Rétablir',
    selectAll: 'Tout sélectionner',
    duplicate: 'Dupliquer',
    delete: 'Supprimer',
    moveSelection: 'Déplacer la sélection',
    closePolygon: 'Fermer le polygone',
    cancel: 'Annuler / quitter',
    addToSelection: 'Ajouter à la sélection',
    markersOnly: 'Marqueurs seuls (tracé)',
  },
  glyphs: { submenu: '›', check: '✓', none: '∅', separator: '·' },
  modKey: { mac: '⌘', other: 'Ctrl+' },
  keys: {
    escape: 'Échap',
    space: 'Espace',
    spaceShift: 'Espace+Maj',
    shiftDrag: 'Maj + glisser',
    enter: 'Entrée',
    arrows: 'Flèches',
    backspace: '⌫',
    shiftClick: 'Maj + clic',
    altOrCmd: 'Alt / ⌘',
    /** Glyphe Maj seul, pour composer un raccourci affiché (⇧Z). */
    shift: '⇧',
    /** Nom de la touche Maj, seule (accélération du déplacement). */
    shiftKey: 'Maj',
  },
  format: {
    shortcut: '{label} ({key})',
  },
  // Système métrique. Pour de l'impérial, `imperialMeasure` ci-dessous s'y substitue
  // d'un bloc — il n'y a pas de conversion à refaire côté application.
  measure: {
    major: '{value} km',
    minor: '{value} m',
    majorThreshold: 1000,
    majorFactor: 1000,
    minorFactor: 1,
    majorDecimals: 2,
    minorDecimals: 0,
    numberLocale: 'auto',
  },
  duration: {
    // Les deux bascules sexagésimales étaient en dur, contrairement à celles de
    // distance : une locale ne pouvait pas préférer « 90 min » à « 1 h 30 ».
    minorThreshold: 60,
    majorThreshold: 60,
    seconds: '{value} s',
    minutes: '{value} min',
    hours: '{h} h',
    hoursMinutes: '{h} h {m}',
  },
  stats: {
    title: 'Infos',
    sections: { camera: 'Caméra', content: 'Contenu affiché', render: 'Rendu', tiles: 'Tuiles et mémoire' },
    // Ces libellés-ci ne sont PAS abrégés, contrairement à `readout` : le panneau se lit
    // posément, une ligne par grandeur, là où le bloc se lisait d'un coup d'œil en
    // naviguant. Abréger ferait deviner ce qu'on est venu vérifier.
    markersVisible: 'markers affichés',
    markersTotal: 'markers au total',
    clusters: 'pastilles de regroupement',
    shapes: 'formes',
    paths: 'tracés',
    links: 'liens',
    drawings: 'dessins',
    fps: 'images par seconde',
    paintedRatio: 'frames peintes',
    drawCalls: 'appels de rendu',
    triangles: 'triangles',
    textures: 'textures',
    geometries: 'géométries',
    resolutionScale: 'échelle de résolution',
    tilesCached: 'tuiles en cache',
    tilesInflight: 'tuiles en chargement',
    tileBytes: 'mémoire des tuiles',
    workers: 'workers d’extrusion',
    percentFormat: '{value} %',
    byteUnits: ['o', 'Ko', 'Mo', 'Go'],
  },
  readout: {
    title: 'Position de la caméra',
    // Abrégés : le bloc se lit d'un coup d'œil pendant qu'on navigue, il ne se lit pas
    // comme une fiche. Un hôte qui veut « Altitude » n'a qu'à le dire.
    altitude: 'alt',
    latitude: 'lat',
    longitude: 'lng',
    heading: 'cap',
    tilt: 'incl',
    zoom: 'zoom',
    // Degré collé au nombre : la notation des relevés, et le seul à porter une unité.
    degreeFormat: '{value}°',
    degreeDecimals: 0,
    coordDecimals: 5,
    zoomDecimals: 1,
    // Point décimal même en français : cf. le JSDoc du champ — une coordonnée se recopie.
    numberLocale: 'en-US',
  },
  relations: {
    menuRoot: 'Distance autour',
    pending: '…',
    unavailable: 'Temps indisponible',
    linkLabel: '{distance} · {duration}',
    fastestGroup: 'Les plus rapides',
    fastest: 'Les {count} plus rapides',
    radiusGroup: 'Dans un rayon',
    radius: 'Dans {radius}',
    targetCount: '{count}',
    tooWide: '{count} !',
    noTargets: 'aucun',
    clusterAggregate: '{count} éléments',
    statusRelation: '{source} → {targets}',
    clear: 'Supprimer',
    removeRoute: 'Fermer l’itinéraire',
    modes: {
      DRIVE: 'En voiture',
      WALK: 'À pied',
      BICYCLE: 'À vélo',
      TWO_WHEELER: 'En deux-roues',
      TRANSIT: 'En transports',
    },
  },
  pinned: {
    add: 'Ajouter un marqueur',
    remove: 'Supprimer',
    collapse: 'Réduire',
    expand: 'Développer',
    title: 'Favoris',
  },
  // Règle française : 0 et 1 au singulier. `Intl.PluralRules` n'est pas utilisé par
  // défaut — il exige une locale, que la lib n'a pas à deviner à la place de l'hôte.
  plural: (count) => (count > 1 ? 'other' : 'one'),
  errors: {
    outsideMap: 'Ce composant doit être utilisé à l’intérieur de <Map>',
    drawingRequired: 'useDrawing nécessite le dessin : il est retiré par <Map draw={false}>',
    lensRequired: 'useLens nécessite la loupe : elle est retirée par <Map toolbar={{ lens: false }}>',
  },
}

/**
 * Jeu de mesures **impérial**, à substituer en bloc :
 *
 * ```tsx
 * <MapProvider labels={{ measure: imperialMeasure }}>
 * ```
 *
 * Les gabarits restent traduisibles (`'{value} mi'` devient `'{value} milles'` en
 * français canadien) : ce bloc ne fixe que le système d'unités, pas la langue.
 *
 * Bascule à 1 mile — en dessous on lit des pieds, au-dessus des miles. Les valeurs
 * d'entrée sont en mètres, comme toujours : `1609.344 m = 1 mi`, `0.3048 m = 1 ft`.
 */
export const imperialMeasure: MapLabels['measure'] = {
  major: '{value} mi',
  minor: '{value} ft',
  majorThreshold: 1609.344,
  majorFactor: 1609.344,
  minorFactor: 0.3048,
  majorDecimals: 1,
  minorDecimals: 0,
  numberLocale: 'auto',
}
