/* ══════════════════ LIBELLÉS FRANÇAIS DE `MapConfig` ══════════════════
   Les noms de clés sont anglais (c'est l'API), le panneau est français : sans cette
   table, l'onglet Config afficherait « shape hit tolerance » à côté de « sévérité » et
   « poser une alerte ». Un panneau à moitié traduit se lit plus mal qu'un panneau
   entièrement anglais.

   Règles tenues ici :
   - court — un libellé qui déborde de la colonne ne se lit pas ;
   - PARLANT — ce que le réglage FAIT, pas la traduction mot à mot de sa clé
     (`backoffAuthMs` → « attente après refus d’identité », pas « backoff auth ») ;
   - l'unité entre parenthèses, jamais dans le mot ;
   - le contexte vient du dossier : dans « Cache », `ttlMs` est « durée de vie », il n'a
     pas à répéter « du cache ».

   Une clé sans entrée retombe sur `autoLabel` (dérivé du nom, donc anglais) :
   `configLabels.test.ts` échoue tant que c'est le cas. */

/** Dossiers — un par nœud de l'arbre `MapConfig`. */
export const FOLDER_LABELS: Readonly<Record<string, string>> = {
  providers: 'Fournisseurs tiers',
  'providers.internal': 'Serveur interne',
  'providers.tiles': 'Tuiles 2D',
  'providers.routing': 'Itinéraires',
  'providers.routing.cache': 'Cache',
  'providers.routing.presets': 'Paliers proposés',
  'providers.places': 'Recherche de lieux',
  'providers.tiles3d': 'Tuiles 3D',
  'providers.buildings': 'Bâtiments 3D',
  'providers.symbols': 'Symboles tactiques',
  'providers.templates': 'Templates de dessin',
  'providers.templates.headers': 'En-têtes HTTP',
  'providers.templates.fetch': 'Politique réseau',

  interaction: 'Interaction',
  'interaction.lens': 'Loupe',
  'interaction.history': 'Annulation',
  'interaction.menu': 'Menus',
  'interaction.buildingPick': 'Sélection de bâtiment',
  'interaction.tooltip': 'Infobulle de cluster',
  'interaction.spiderfy': 'Éclatement en éventail',
  'interaction.clusterOpenZoom': 'Ouverture d’un cluster',
  'interaction.symbols': 'Symboles',
  'interaction.shortcuts': 'Raccourcis clavier',
  'interaction.shortcuts.controls': 'Navigation',
  'interaction.shortcuts.navigate': 'Déplacement au clavier',
  'interaction.shortcuts.draw': 'Outils de dessin',
  'interaction.shortcuts.edit': 'Édition',
  'interaction.shortcuts.lens': 'Loupe',

  performance: 'Performance',
  'performance.cameraMoveEpsilon': 'Seuil de mouvement caméra',
  'performance.groundSample': 'Échantillonnage du sol',
  'performance.resettle': 'Re-échantillonnage',
  'performance.adaptiveResolution': 'Résolution adaptative',
  'performance.renderOnDemand': 'Rendu à la demande',
  'performance.overlayDepth': 'Profondeur des overlays',
  'performance.relations': 'Relations',

  style: 'Style',
  'style.zIndex': 'Empilement des surfaces',

  camera: 'Caméra',
  'camera.dragSpeed': 'Vitesse de déplacement',
  'camera.zoomFactor': 'Facteur par cran de zoom',
  'camera.keyPan': 'Déplacement au clavier',
  'camera.followAltitude': 'Altitude du mode suivi',
  'camera.fitBounds': 'Cadrage automatique',

  clustering: 'Regroupement',
  markers: 'Markers',

  data: 'Données',
  'data.storageKeys': 'Clés de stockage',
  'data.search': 'Boîte de recherche',

  startup: 'Démarrage',

  sky: 'Ciel',
  'sky.clouds': 'Nuages',
  'sky.fade': 'Fondu (altitude)',
  pedestrian: 'Mode piéton',
  'pedestrian.collision': 'Collision',
  'pedestrian.placement': 'Placement',
  'pedestrian.headBob': 'Balancement',
  'pedestrian.transitions': 'Transitions',
  'interaction.shortcuts.pedestrian': 'Mode piéton',

  graticule: 'Grille de coordonnées',
  'graticule.remarkable': 'Lignes remarquables',
  'graticule.tiltFade': 'Fondu à l’inclinaison',
  'graticule.labels': 'Étiquettes',

  catalog: 'Catalogue',
}

/** Feuilles — les 196 de `defaultConfig`, plus les 3 clés optionnelles du type. */
export const CONFIG_LABELS: Readonly<Record<string, string>> = {
  // ── providers.tiles ────────────────────────────────────────────────────────
  'providers.internal.origin': 'origine du serveur',
  'providers.internal.elevationEpsilon': 'seuil de reconstruction (m)',
  'providers.tiles.provider': 'fournisseur de tuiles',
  'providers.tiles.internalTileUrl': 'gabarit d’URL interne',
  'providers.tiles.style': 'style interne',
  'providers.tiles.retina': 'tuiles double densité',
  'providers.tiles.lodRing': 'anneau de la cascade (tuiles)',
  'providers.tiles.baseZoom': 'zoom du niveau de base',
  'providers.tiles.fillPoles': 'remplir les calottes polaires',
  'providers.tiles.maxZoom': 'zoom maximal demandé',
  'providers.tiles.language': 'langue des libellés',
  'providers.tiles.region': 'biais régional',
  'providers.tiles.mapType': 'fond de carte',
  'providers.tiles.layerTypes': 'calques demandés',
  'providers.tiles.sessionUrl': 'URL de session',
  'providers.tiles.tileUrl': 'gabarit d’URL de tuile',
  'providers.tiles.backoffAuthMs': 'attente après refus d’identité (ms)',
  'providers.tiles.backoffTransientMs': 'attente après panne (ms)',
  'providers.tiles.maxTiles': 'cache de textures (tuiles)',
  'providers.tiles.maxBytes': 'cache de textures (Mio)',
  'providers.tiles.evictEvery': 'éviction : une frame sur',
  'providers.tiles.evictSlack': 'éviction forcée au-delà de (tuiles)',
  'providers.tiles.mountPerFrame': 'tuiles montées par frame',
  'providers.tiles.maxInflight': 'téléchargements simultanés',
  'providers.tiles.margin': 'anneau de préchargement',
  'providers.tiles.maxRequest': 'budget de tuiles par zoom',
  'providers.tiles.uniformDetail': 'détail uniforme (un seul niveau)',
  'providers.tiles.uniformMaxSpread': 'écart toléré avant cascade (crans)',
  'providers.tiles.maxAttempts': 'essais par tuile',
  'providers.tiles.retryDelays': 'délais entre essais (ms)',

  // ── providers.routing ──────────────────────────────────────────────────────
  'providers.routing.matrixUrl': 'URL de la matrice',
  'providers.routing.routesUrl': 'URL des itinéraires',
  'providers.routing.matrixFields': 'champs de la matrice',
  'providers.routing.routeFields': 'champs d’un itinéraire',
  'providers.routing.routingPreference': 'qualité de routage',
  'providers.routing.languageCode': 'langue des textes',
  'providers.routing.regionCode': 'biais régional',
  'providers.routing.alternatives': 'itinéraires alternatifs',
  'providers.routing.timeoutMs': 'délai d’abandon (ms)',
  'providers.routing.retries': 'réessais',
  'providers.routing.backoffMs': 'attente avant réessai (ms)',
  'providers.routing.cache.ttlMs': 'durée de vie (ms)',
  'providers.routing.cache.cellMeters': 'tolérance de dérive (m)',
  'providers.routing.cache.maxEntries': 'entrées maximum',
  'providers.routing.fastestOversample': 'candidats interrogés (×)',
  'providers.routing.staleMeters': 'dérive avant recalcul (m)',
  'providers.routing.refreshIntervalMs': 'intervalle de recalcul (ms)',
  'providers.routing.presets.fastest': 'paliers « N plus rapides »',
  'providers.routing.presets.radius': 'paliers de rayon (m)',
  'providers.routing.units': 'système d’unités',
  'providers.routing.headers': 'en-têtes HTTP (JSON)',

  // ── providers.places ───────────────────────────────────────────────────────
  'providers.places.url': 'URL de recherche',
  'providers.places.fields': 'champs demandés',
  'providers.places.pageSize': 'résultats demandés',
  'providers.places.pageSizeRange': 'bornes acceptées',
  'providers.places.languageCode': 'langue des résultats',
  'providers.places.regionCode': 'biais régional',
  'providers.places.timeoutMs': 'délai d’abandon (ms)',
  'providers.places.retries': 'réessais',
  'providers.places.backoffMs': 'attente avant réessai (ms)',
  'providers.places.headers': 'en-têtes HTTP (JSON)',

  // ── providers.templates ────────────────────────────────────────────────────
  'providers.templates.baseUrl': 'URL de l’API (vide = local)',
  'providers.templates.fetch.timeoutMs': 'délai d’abandon (ms)',
  'providers.templates.fetch.retries': 'réessais',
  'providers.templates.fetch.backoffMs': 'attente avant réessai (ms)',
  'providers.templates.categories': 'catégories offertes',
  'providers.templates.defaultCategories': 'catégories cochées par défaut',
  'providers.templates.defaultApply': 'mode d’application par défaut',
  'providers.templates.allowExport': 'export/import .m3dt',
  'providers.templates.saveView': 'proposer de mémoriser la vue',
  'providers.templates.defaultSaveView': 'vue cochée par défaut',
  'providers.templates.applyView': 'rejouer la vue au chargement',
  'providers.templates.viewFlyDuration': 'durée du trajet vers la vue (s)',

  // ── providers, divers ──────────────────────────────────────────────────────
  'providers.tiles3d.provider': 'fournisseur du volume',

  // ── providers.buildings ────────────────────────────────────────────────────
  'providers.buildings.tileUrl': 'gabarit d’URL vectorielle',
  'providers.buildings.sourceLayer': 'couche des emprises',
  'providers.buildings.heightField': 'attribut de hauteur',
  'providers.buildings.minHeightField': 'attribut de hauteur de base',
  'providers.buildings.hideField': 'attribut d’exclusion',
  'providers.buildings.colorField': 'attribut de couleur',
  'providers.buildings.defaultHeight': 'hauteur par défaut (m)',
  'providers.buildings.maxHeight': 'hauteur maximale retenue (m)',
  'providers.buildings.positionPrecision': 'précision des positions',
  'providers.buildings.zoom': 'zoom des tuiles vectorielles',
  'providers.buildings.maxViewAltitude': 'altitude max d’affichage (m)',
  'providers.buildings.requestAltitudeFactor': 'préchargement (× altitude)',
  'providers.buildings.maxViewDistance': 'portée du volume (m)',
  'providers.buildings.margin': 'anneau de préchargement',
  'providers.buildings.maxTiles': 'cache de tuiles extrudées',
  'providers.buildings.maxBytes': 'plafond mémoire du cache (Mio)',
  'providers.buildings.evictEvery': 'éviction : une frame sur',
  'providers.buildings.evictSlack': 'éviction forcée au-delà de (tuiles)',
  'providers.buildings.mountPerFrame': 'tuiles montées par frame',
  'providers.buildings.maxInflight': 'téléchargements simultanés',
  'providers.buildings.maxRequest': 'budget de tuiles par vue',
  'providers.buildings.maxAttempts': 'essais par tuile',
  'providers.buildings.retryDelays': 'délais entre essais (ms)',
  'providers.buildings.pickFields': 'attributs remontés au clic',
  'providers.tiles3d.cesiumIonAssetId': 'asset Cesium Ion',
  'providers.tiles3d.hideVolumeWhenClamped': 'masquer la 3D si vue non couverte',
  'providers.tiles3d.volumeFadeMs': 'durée du fondu (ms)',
  'providers.symbols.cacheMaxEntries': 'cache de vignettes',

  // ── interaction ────────────────────────────────────────────────────────────
  'interaction.shapeHitTolerancePx': 'tolérance clic forme (px)',
  'interaction.linkHitTolerancePx': 'tolérance clic lien (px)',
  'interaction.closeSnapPx': 'aimant de fermeture (px)',
  'interaction.clickSlopPx': 'seuil clic → glissé (px)',
  'interaction.dragSlopPx': 'seuil de saisie (px)',
  'interaction.repositionSlopPx': 'seuil de repositionnement (px)',
  'interaction.cleanClickPx': 'clic net maximum (px)',
  'interaction.lassoMinStepPx': 'pas du lasso (px)',
  'interaction.duplicateOffsetPx': 'décalage des copies (px)',
  'interaction.longPressMs': 'appui long (ms)',
  'interaction.minScale': 'échelle minimale',
  'interaction.damping': 'inertie des contrôles',
  'interaction.lens.minDragPx': 'glissé minimal (px)',
  'interaction.lens.minSizePx': 'côté minimal (px)',
  'interaction.history.coalesceMs': 'fusion des actions (ms)',
  'interaction.history.depth': 'profondeur d’annulation',
  'interaction.menu.hoverIntentMs': 'survol avant ouverture (ms)',
  'interaction.menu.submenuCloseMs': 'grâce avant fermeture (ms)',
  'interaction.buildingPick.cursor': 'curseur de l’outil',
  'interaction.hubHitTolerancePx': 'tolérance clic socle (px)',
  'interaction.repositionHitPx': 'cible du point au sol (px)',
  'interaction.clickSuppressMs': 'clic avalé après geste (ms)',
  'interaction.freehandMinStepPx': 'pas du main levée (px)',
  'interaction.targetZoom': 'zoom de ciblage',
  'interaction.pinnedFlyZoom': 'zoom vers un favori',
  'interaction.drawToolbarMinZoom': 'zoom mini barre de dessin',
  'interaction.barMinScale': 'compactage mini des barres',
  'interaction.tooltip.flipBelowPx': 'bascule sous le pointeur (px)',
  'interaction.tooltip.clampMarginPx': 'marge de bord (px)',
  'interaction.tooltip.offsetBelowPx': 'décalage vers le bas (px)',
  'interaction.tooltip.offsetAbovePx': 'décalage vers le haut (px)',
  'interaction.spiderfy.pairRadiusRatio': 'rayon d’une paire (ratio)',
  'interaction.spiderfy.minRingRatio': 'rayon mini de couronne (×)',
  'interaction.spiderfy.gapPx': 'espacement (px)',
  'interaction.spiderfy.zoomEpsilon': 'hystérésis de zoom',
  'interaction.clusterOpenZoom.expansion': 'marge d’éclatement',
  'interaction.clusterOpenZoom.max': 'marge au-delà du plafond',
  'interaction.symbols.sizePx': 'taille posée (px)',
  'interaction.symbols.previewSizePx': 'taille en palette (px)',

  // ── interaction.shortcuts ──────────────────────────────────────────────────
  'interaction.shortcuts.controls.north': 'nord et vue du dessus',
  'interaction.shortcuts.controls.zoomIn': 'zoom avant',
  'interaction.shortcuts.controls.zoomOut': 'zoom arrière',
  'interaction.shortcuts.controls.tilt': 'inclinaison',
  'interaction.shortcuts.controls.globe': 'vue globe',
  'interaction.shortcuts.controls.layers': 'panneau Couches',
  'interaction.shortcuts.controls.fullscreen': 'plein écran',
  'interaction.shortcuts.controls.basemap': 'bascule 3D / plan',
  'interaction.shortcuts.controls.traffic': 'calque trafic',

  'interaction.shortcuts.draw.select': 'sélection',
  'interaction.shortcuts.draw.selectRect': 'sélection rectangle',
  'interaction.shortcuts.draw.selectPoly': 'sélection polygone',
  'interaction.shortcuts.draw.selectBuilding': 'sélection d’un bâtiment',
  'interaction.shortcuts.draw.selectLasso': 'sélection lasso',
  'interaction.shortcuts.draw.line': 'ligne',
  'interaction.shortcuts.draw.polygon': 'polygone',
  'interaction.shortcuts.draw.rect': 'rectangle',
  'interaction.shortcuts.draw.circle': 'cercle',
  'interaction.shortcuts.draw.freehand': 'main levée',
  'interaction.shortcuts.draw.arrow': 'flèche',
  'interaction.shortcuts.draw.measure': 'règle de mesure',
  'interaction.shortcuts.draw.erase': 'gomme',
  'interaction.shortcuts.draw.symbol': 'palette de symboles',

  'interaction.shortcuts.edit.undo': 'annuler',
  'interaction.shortcuts.edit.redo': 'rétablir',
  'interaction.shortcuts.edit.redoAlt': 'rétablir (variante)',
  'interaction.shortcuts.edit.selectAll': 'tout sélectionner',
  'interaction.shortcuts.edit.duplicate': 'dupliquer',
  'interaction.shortcuts.edit.delete': 'supprimer (touches)',
  'interaction.shortcuts.edit.closePolygon': 'fermer le polygone',
  'interaction.shortcuts.edit.nudgePx': 'pas clavier (px)',
  'interaction.shortcuts.edit.nudgeFastPx': 'pas clavier rapide (px)',
  'interaction.shortcuts.lens.toggle': 'bascule de la loupe',

  // ── performance ────────────────────────────────────────────────────────────
  'performance.textureAnisotropy': 'filtrage anisotrope (0 = max)',
  'performance.pixelRatio': 'densité de pixels',
  'performance.antialias': 'anticrénelage',
  'performance.powerPreference': 'arbitrage GPU',
  'performance.adaptiveResolution.enabled': 'résolution adaptative',
  'performance.adaptiveResolution.targetFrameMs': 'cadence visée (ms/frame)',
  'performance.adaptiveResolution.minRatio': 'plancher de résolution',
  'performance.adaptiveResolution.step': 'pas d’ajustement',
  'performance.adaptiveResolution.sampleFrames': 'fenêtre de mesure (frames)',
  'performance.renderOnDemand.enabled': 'rendu à la demande',
  'performance.renderOnDemand.idleFrames': 'frames après demande',
  'performance.renderOnDemand.maxIdleMs': 'frame de sécurité (ms)',
  'performance.overlayDepth.nearMeters': 'plan proche des overlays (m)',
  'performance.overlayDepth.farMeters': 'plan lointain des overlays (m)',
  'performance.boundsPickGrid': 'grille de raycasts',
  'performance.boundsMargin': 'marge du cadre émis',
  'performance.viewportSettleFrames': 'immobilité avant émission (frames)',
  'performance.markerRecomputeMs': 'recalcul des clusters (ms)',
  'performance.readoutRefreshMs': 'bloc de position (ms)',
  'performance.cameraMoveEpsilon.deg': 'écart lat/lng (°)',
  'performance.cameraMoveEpsilon.altitudeRatio': 'écart d’altitude (ratio)',
  'performance.cameraMoveEpsilon.altitudeMinMeters': 'plancher d’altitude (m)',
  'performance.groundSample.ttlMs': 'validité d’un échantillon (ms)',
  'performance.groundSample.cellDeg': 'quantification du cache (°)',
  'performance.groundSample.cacheMaxCells': 'cellules avant purge',
  'performance.groundSample.rayOriginMeters': 'départ du rayon (m)',
  'performance.groundSample.rayFarMeters': 'portée du rayon (m)',
  'performance.groundSample.radiusMeters': 'rayon de la couronne (m)',
  'performance.groundSample.samples': 'tirs par couronne',
  'performance.markerCullMarginPx': 'marge de masquage (px)',
  'performance.markerZoomBand': 'hystérésis du seuil de zoom',
  'performance.resettle.batch': 'éléments par passe',
  'performance.resettle.retryFrames': 'retentative (frames)',
  'performance.resettle.mppBand': 'hystérésis de résolution',
  'performance.resettle.windowFrames': 'fenêtre après mouvement (frames)',
  'performance.resettle.spawnWindowFrames': 'fenêtre à la création (frames)',
  'performance.resettle.everyNFrames': 'cadence des passes (frames)',
  'performance.relations.maxSteps': 'subdivision max d’un arc',
  'performance.relations.stepMeters': 'pas d’échantillonnage (m)',
  'performance.relations.fanMaxLegs': 'liens max dans l’éventail',
  'performance.relations.zoomBand': 'hystérésis de regroupement',
  'performance.circleSegments': 'segments d’un cercle',
  'performance.groundHeightRange': 'altitudes admises (m)',

  // ── style.zIndex ───────────────────────────────────────────────────────────
  'style.zIndex.mapOverlay': 'surfaces de la carte',
  'style.zIndex.relationBar': 'barre de relation',
  'style.zIndex.editOverlay': 'poignées d’édition',
  'style.zIndex.floatingHud': 'HUD flottant',
  'style.zIndex.markerSelected': 'marker sélectionné',
  'style.zIndex.tooltip': 'infobulles',
  'style.zIndex.listMenu': 'menu d’une ligne',
  'style.zIndex.dock': 'dock des favoris',
  'style.zIndex.ui': 'barres et panneaux',
  'style.zIndex.menu': 'menus contextuels',
  'style.zIndex.modal': 'modales et confirmations',

  // ── camera ─────────────────────────────────────────────────────────────────
  'camera.minZoom': 'zoom minimal',
  'camera.maxZoom': 'zoom maximal en plan',
  'camera.maxZoom3d': 'zoom maximal en 3D (plancher)',
  'camera.maxTilt': 'inclinaison max (rad)',
  'camera.zoomStep': 'pas de la molette',
  'camera.dragSpeed.min': 'au ras du sol',
  'camera.dragSpeed.max': 'en vue globe',
  'camera.fov': 'champ de vision (°)',
  'camera.maxTilt3d': 'inclinaison max en 3D (rad)',
  'camera.maxTilt2d': 'inclinaison max en plan (rad)',
  'camera.tiltStep': 'pas d’inclinaison (rad)',
  'camera.zoomFactor.in': 'zoom avant',
  'camera.zoomFactor.out': 'zoom arrière',
  'camera.maxDistanceFactor': 'distance max (rayons terrestres)',
  'camera.maxAltitudeFactor': 'altitude max des vols (rayons)',
  'camera.minGroundClearance': 'garde au sol (m)',
  'camera.keyPan.speed': 'vitesse (hauteurs-sol / s)',
  'camera.keyPan.boost': 'accélération (×, avec Maj)',
  'interaction.shortcuts.navigate.forward': 'avancer',
  'interaction.shortcuts.navigate.backward': 'reculer',
  'interaction.shortcuts.navigate.left': 'vers la gauche',
  'interaction.shortcuts.navigate.right': 'vers la droite',
  'interaction.shortcuts.navigate.boost': 'accélérer (maintenu)',
  'camera.followAltitude.min': 'minimale (m)',
  'camera.followAltitude.max': 'maximale (m)',
  'camera.fitBounds.margin': 'respiration',
  'camera.fitBounds.minAltitude': 'altitude minimale (m)',
  'camera.fitBounds.maxAltitude': 'altitude maximale (m)',

  // ── clustering / markers ───────────────────────────────────────────────────
  'clustering.radius': 'rayon de regroupement (px)',
  'clustering.minPoints': 'points minimum',
  'clustering.maxZoom': 'zoom max de regroupement',
  'clustering.levelQuantization': 'quantification du zoom',
  'clustering.spiderfyZoom': 'zoom d’éclatement',
  'markers.staticMinZoom': 'zoom mini du décor',

  // ── data ───────────────────────────────────────────────────────────────────
  'data.viewportDebounceMs': 'anti-rebond du cadre (ms)',
  'data.positionSaveDebounceMs': 'anti-rebond de sauvegarde (ms)',
  'data.storageKeys.tagFilter': 'filtre Couches',
  'data.storageKeys.drawSettings': 'réglages de dessin',
  'data.storageKeys.searchHistory': 'historique de recherche',
  'data.storageKeys.plugins': 'état des plugins',
  'data.storageKeys.templates': 'templates de dessin',
  'data.storageKeys.catalog': 'éléments de catalogue affichés',
  'data.storageKeys.catalogSettings': 'réglages du catalogue',
  'data.search.minQuery': 'saisie minimale',
  'data.search.debounceMs': 'anti-rebond de frappe (ms)',
  'data.search.limitPerGroup': 'résultats par rubrique',
  'data.search.historySize': 'entrées d’historique',
  'data.search.flyAltitude': 'altitude du vol (m)',
  'data.search.fitPadding': 'respiration du cadrage (px)',
  'data.search.resolveLimit': 're-résolutions max',

  // ── startup ────────────────────────────────────────────────────────────────
  'startup.introDuration': 'durée du vol d’intro (s)',
  'startup.introMaxWaitMs': 'attente des tuiles (ms)',
  'startup.readyMaxWaitMs': 'attente avant « prêt » (ms)',
  'startup.introFadeMs': 'fondu de fin (ms)',
  'startup.introAltitudeFactor': 'altitude de départ (rayons)',
  'startup.fallbackSize': 'taille de repli (px)',

  // ── sky ────────────────────────────────────────────────────────────────────
  'sky.enabled': 'ciel atmosphérique',
  'sky.turbidity': 'turbidité (voile)',
  'sky.rayleigh': 'bleu du ciel (Rayleigh)',
  'sky.mieCoefficient': 'halo solaire (Mie)',
  'sky.mieDirectionalG': 'concentration du halo',
  'sky.clouds.coverage': 'couverture',
  'sky.clouds.density': 'densité',
  'sky.clouds.scale': 'échelle du motif',
  'sky.clouds.elevation': 'élévation',
  'sky.fade.start': 'apparition (m)',
  'sky.fade.end': 'plein ciel (m)',
  'sky.date': 'instant du soleil (0 = maintenant)',

  // ── mode piéton ────────────────────────────────────────────────────────────
  'pedestrian.eyeHeightMeters': 'hauteur des yeux (m)',
  'pedestrian.walkSpeed': 'vitesse de marche (m/s)',
  'pedestrian.sprintFactor': 'facteur de course',
  'pedestrian.lookSpeed': 'sensibilité du regard',
  'pedestrian.invertY': 'inverser l’axe vertical',
  'pedestrian.invertX': 'inverser l’axe horizontal',
  'pedestrian.pitchMaxDeg': 'regard vertical maxi (°)',
  'pedestrian.viewDistanceMeters': 'distance de vue (m)',
  'pedestrian.fogStartMeters': 'début du brouillard (m)',
  'pedestrian.nearMeters': 'plan proche (m)',
  'pedestrian.groundProbeMeters': 'portée du rayon de sol (m)',
  'pedestrian.tileDetailDistanceMeters': 'distance de référence du détail (m)',
  'pedestrian.tileRefreshMs': 'cadence de chargement (ms)',
  'pedestrian.groundSmoothing': 'lissage du sol (s)',
  'pedestrian.collision.radiusMeters': 'rayon du corps (m)',
  'pedestrian.collision.feelers': 'nombre de palpeurs',
  'pedestrian.collision.feelerMarginMeters': 'marge des palpeurs (m)',
  'pedestrian.collision.maxStepHeightMeters': 'marche franchissable (m)',
  'pedestrian.placement.maxRoofDeltaMeters': 'écart toit maxi (m)',
  'pedestrian.placement.ringRadiusMeters': 'rayon de la couronne (m)',
  'pedestrian.placement.refreshMs': 'cadence de validation (ms)',
  'pedestrian.placement.refreshSlopPx': 'seuil de revalidation (px)',
  'pedestrian.headBob.enabled': 'balancement de marche',
  'pedestrian.headBob.amplitudeMeters': 'amplitude (m)',
  'pedestrian.headBob.frequency': 'fréquence (Hz)',
  'pedestrian.transitions.enterMs': 'durée de plongée (ms)',
  'pedestrian.transitions.exitMs': 'durée de remontée (ms)',
  'interaction.shortcuts.controls.graticule': 'grille de coordonnées',
  'interaction.shortcuts.controls.pedestrian': 'mode piéton',
  'interaction.shortcuts.pedestrian.immersion': 'basculer l’immersion',

  // ── grille de coordonnées ──────────────────────────────────────────────────
  'graticule.enabled': 'afficher au démarrage',
  'graticule.targetLines': 'lignes visées à l’écran',
  'graticule.levelHysteresis': 'bande morte de la maille',
  'graticule.levelRangeDeg': 'bornes de maille (°)',
  'graticule.segmentsPerLine': 'segments par ligne',
  'graticule.maxLines': 'lignes max par axe',
  'graticule.bandScreens': 'emprise construite (écrans)',
  'graticule.latLimitDeg': 'arrêt aux pôles (°)',
  'graticule.heightOffsetMeters': 'décalage vertical (m)',
  'graticule.heightToleranceMeters': 'dérive tolérée (m)',
  'graticule.opacity': 'opacité des lignes',
  'graticule.remarkableOpacity': 'opacité des remarquables',
  'graticule.dash': 'pointillé (m)',
  'graticule.remarkable.enabled': 'afficher les remarquables',
  'graticule.remarkable.parallels': 'parallèles remarquables',
  'graticule.remarkable.meridians': 'méridiens remarquables',
  'graticule.tiltFade.start': 'début du fondu (fraction)',
  'graticule.tiltFade.end': 'disparition (fraction)',
  'graticule.fadeMs': 'durée du fondu (ms)',
  'graticule.levelFadeMs': 'fondu de maille (ms)',
  'graticule.labels.enabled': 'afficher les étiquettes',
  'graticule.labels.placement': 'placement',
  'graticule.labels.maxLabels': 'étiquettes max',
  'graticule.labels.spacingPx': 'écart minimal (px)',
  'graticule.labels.rotate': 'suivre l’angle de la ligne',
  'graticule.labels.format': 'format des coordonnées',
  'graticule.labels.remarkableNames': 'nommer les remarquables',
  'graticule.labels.idleOpacity': 'opacité au repos',
  'graticule.labels.hoverPaddingPx': 'marge de survol (px)',
  'style.zIndex.graticuleLabel': 'étiquettes du graticule',

  // ── catalog ────────────────────────────────────────────────────────────────
  'catalog.pageSize': 'éléments par page',
  'catalog.debounceMs': 'anti-rebond de frappe (ms)',
  'catalog.maxInlineActions': 'actions en ligne par élément',
}
